document.writeln(" <!-- info section -->");
document.writeln(" <section class=\'info_section\'>");
document.writeln("    <div class=\'container \'>");
document.writeln("      <div class=\'row pb-4\'>");
document.writeln("        <div class=\'col-md-4 info_logo\'>");
document.writeln("          <h2>");
document.writeln("           Baiheng Wu");
document.writeln("          </h2>");
document.writeln("          <p>");
document.writeln("          </p>");
document.writeln("        </div>");
document.writeln("        <div class=\'col-md-4 info_address\'>");
document.writeln("          <h5>");
document.writeln("            Contact");
document.writeln("          </h5>");
document.writeln("          <p>");
document.writeln("              Larsgårdsvegen 2, 6009 Ålesund, Norway");
document.writeln("          </p>");
document.writeln("          <p>");
document.writeln("            (+47) 93966566");
document.writeln("          </p>");
document.writeln("          <p>");
document.writeln("            <a href=\'mailto:baiheng.wu@ntnu.no\' target=\'_blank\'>baiheng.wu@ntnu.no</a>");
document.writeln("          </p><br><br>");
document.writeln("        </div>");
document.writeln("        <!-- <div class=\'col-md-4 info_news\'>");
document.writeln("          <h5>");
document.writeln("            Newsletter");
document.writeln("          </h5>");
document.writeln("          <form action=\'\'>");
document.writeln("            <div>");
document.writeln("              <input type=\'email\' placeholder=\'Enter your email\'>");
document.writeln("            </div>");
document.writeln("            <div>");
document.writeln("              <button type=\'submit\'>");
document.writeln("                Subscribe");
document.writeln("              </button>");
document.writeln("            </div>");
document.writeln("          </form>");
document.writeln("        </div> -->");
document.writeln("");
document.writeln("<!--       </div>");
document.writeln("    ");
document.writeln("      <div> -->");
document.writeln("        <div class=\'col-md-4 info_social\'>");
document.writeln("          <div>");
document.writeln("           <a href=\'https://scholar.google.com/citations?user=fS7hgA4AAAAJ\' target=\'_blank\'>");
document.writeln("              <img src=\'images/google.png\' alt=\'\'>");
document.writeln("           </a>");
document.writeln("          </div>");
document.writeln("          <div>");
document.writeln("           <a href=\'https://www.researchgate.net/profile/Baiheng-Wu\' target=\'_blank\'>");
document.writeln("              <img src=\'images/rg.png\' alt=\'\'>");
document.writeln("           </a>");
document.writeln("          </div>");
document.writeln("          <div>");
document.writeln("           <a href=\'https://www.linkedin.com/in/baiheng-wu-109812105/\' target=\'_blank\'>");
document.writeln("              <img src=\'images/linkedin.png\' alt=\'\'>");
document.writeln("           </a>");
document.writeln("          </div>");
document.writeln("          <!-- <div>");
document.writeln("            <a href=\'\'>");
document.writeln("                <img src=\'images/insta.png\' alt=\'\'>");
document.writeln("            </a>");
document.writeln("          </div> -->");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </section>");
document.writeln("  <!-- endsss info section -->");
document.writeln("");
document.writeln("<!-- end contact section -->");
document.writeln("");
document.writeln("<!-- footer section -->");
document.writeln("  <section class=\'container-fluid footer_section\'>");
document.writeln("    <p>");
document.writeln("      Copyright &copy; 2019 All Rights Reserved By");
document.writeln("      <a href=\'https://html.design/\'>Free Html Templates</a>");
document.writeln("    </p>");
document.writeln("  </section>");
document.writeln("  <!-- footer section -->");