document.writeln("    <header class=\'header_section\'>");
document.writeln("      <div class=\'container-fluid\'>");
document.writeln("        <nav class=\'navbar navbar-expand-lg custom_nav-container \'>");
document.writeln("          <a class=\'navbar-brand\' href=\'index.html\'>");
document.writeln("            Baiheng WU\'s HomePage");
document.writeln("          </a>");
document.writeln("          <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\'");
document.writeln("            aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("          </button>");
document.writeln("          <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("            <div class=\'d-flex ml-auto flex-column flex-lg-row align-items-center\'>");
document.writeln("              <ul class=\'navbar-nav  \'>");
document.writeln("                <li class=\'nav-item active\'>");
document.writeln("                  <a class=\'nav-link\' href=\'index.html\'> Home <span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item \'>");
document.writeln("                  <a class=\'nav-link\' href=\'publication.html\'> Publication </a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                  <a class=\'nav-link\' href=\'talk.html\'> Talk </a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                  <a class=\'nav-link\' href=\'cv.html\'> CV </a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("              </ul>");
document.writeln("              <!-- <form class=\'form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0\'>");
document.writeln("                <button class=\'btn  my-2 my-sm-0 nav_search-btn\' type=\'submit\'></button>");
document.writeln("              </form> -->");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("      </div>");
document.writeln("    </header>");