document.writeln("<head>");
document.writeln("  <!-- Basic -->");
document.writeln("  <meta charset=\'utf-8\' />");
document.writeln("  <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\' />");
document.writeln("  <!-- Mobile Metas -->");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\' />");
document.writeln("  <!-- Site Metas -->");
document.writeln("  <meta name=\'keywords\' content=\'\' />");
document.writeln("  <meta name=\'description\' content=\'\' />");
document.writeln("  <meta name=\'author\' content=\'\' />");
document.writeln("");
document.writeln("  <title>Baiheng WU</title>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!-- bootstrap core css -->");
document.writeln("  <link rel=\'stylesheet\' type=\'text/css\' href=\'css/bootstrap.css\' />");
document.writeln("  <!-- fonts style -->");
document.writeln("  <link href=\'https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("  <!-- Custom styles for this template -->");
document.writeln("  <link href=\'css/style.css\' rel=\'stylesheet\' />");
document.writeln("  <link rel=\'stylesheet\' href=\'css/fontawesome-all.min.css\'>");
document.writeln("  <!-- responsive style -->");
document.writeln("  <link href=\'css/responsive.css\' rel=\'stylesheet\' />");
document.writeln("");
document.writeln("  <link rel=\'stylesheet\' href=\'css/css-circular-prog-bar.css\'>");
document.writeln("");
document.writeln("  <link rel=\'shortcut icon\' type=\'image/x-icon\' href=\'images/ntnu_logo.png\'>");
document.writeln("</head>");